# Generated by Django 4.0.5 on 2022-12-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('C', models.FloatField()),
                ('E', models.FloatField()),
                ('A', models.FloatField()),
                ('N', models.FloatField()),
                ('O', models.FloatField()),
            ],
        ),
    ]
